name: dartcode
description: some dart code

environment:
   sdk: ">=2.12.0 <3.0.0"
   
dependencies: 
  json_annotation: ^4.4.0
  http: ^0.13.4
  sprintf: ^4.0.2
  dio: any


dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

